sudo: required

services:
  - docker

before_install:
  - docker build -t akshaya1234/docker-react -f Dockerfile.dev .

script: 
  - docker run akshaya1234/docker-react npm run test -- --coverage

deploy:  
  provider: elasticbeanstalk
  region: "eu-north-1"
  app: "docker"
  env: "Docker-env"
  bucket_name: 